url: "https://sisira.aqclf.xyz"
title: "sisira" 
description: "a design philosophy, being made by sam"
fontcss: "https://aqclf.xyz/comic.css" 
favicon: "https://avatars.githubusercontent.com/u/147059745?s=200&v=4" 
banner: "https://aqclf.xyz/preview.png" 
twitter: "@aquaticcalf"
date_format: "%-d %B %Y" 
